### PR TITLE
[jammy] Rebase on 1:0.9.6.1

### PR DESCRIPTION
**Pull request by crawfxrd**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — DISMISSED** [review]

**Comment by crawfxrd** [comment]
I don't know. Am I missing something in the log?

```
ubuntu-drivers-common
warning: ignoring broken ref refs/remotes/origin/HEAD
```

```
E: Build failure (dpkg-buildpackage died)
ubuntu-drivers-common: 0ed6364bc846556abb12e6449a3f29f256ab7b8d (rebase_jammy): jammy (22.04): amd64: binary failed: exit code: 2
```

**Comment by n3m0-22** [comment]
May resolve [363](https://github.com/pop-os/beta/issues/363)

**Review by n3m0-22 — APPROVED** [review]
This fixes the issues of not being able to install gnome-software and nautilus-share. After installing nautlius-share nautilus no longer crashes when trying to share a folder, but does show this error.
Screenshot from 2022-04-27 14-29-28
I have samba installed the user added to the group and a samba password set, but this error always happens. 

As for gnome-software it installs and uninstalls snap packages fine and does not seem to break anything, but there are some issues. There are missing images, and clicking on any of the categories usually shows blanks or nothing at all. They do on occasion work and apps can be searched for with no problems.

Screenshot from 2022-04-27 14-37-23
Screenshot from 2022-04-27 14-28-05

Screenshot from 2022-04-27 14-27-36

I'm approving assuming none of these are issues to hold this back. I can always retest if they are.

**Comment by wagnerck** [comment]
@n3m0-22 I have a (mostly) working setup for `nautilus-share` here in this other issue: https://github.com/system76/careteam/issues/29

**Pull request merged**
