### PR TITLE
gpu-manager: Wait longer for GPU init

### LINKED ISSUE #160: Oryp6/Oryp7: compute mode doesn't work
In Pop!_OS 20.10, if I switch to the Compute graphics mode and reboot, running `nvidia-smi` hangs completely. This is with the current Nvidia 460.39 driver.

### LINKED ISSUE #259: Oryp6 - Nvidia freezes with "Can't change power state from D3cold to D0"
Sometimes my laptop will completely freeze with the following error logs in journalctl:
```
kernel: nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
kernel: NVRM: GPU at PCI:0000:01:00: GPU-a137dd66-f6a3-7951-1348-c37443697050
kernel: NVRM: Xid (PCI:0000:01:00): 79, pid=7992, GPU has fallen off the bus.
kernel: NVRM: GPU 0000:01:00.0: GPU has fallen off the bus.
kernel: xhci_hcd 0000:01:00.2: can't change power state from D3cold to D0 (config space inaccessible)
kernel: xhci_hcd 0000:01:00.2: can't change power state from D3hot to D0 (config space inaccessible)
kernel: xhci_hcd 0000:01:00.2: Controller not ready at resume -19
kernel: xhci_hcd 0000:01:00.2: PCI post-resume error -19!
kernel: xhci_hcd 0000:01:00.2: HC died; cleaning up
kernel: pci 0000:01:00.3: can't change power state from D3cold to D0 (config space inaccessible)
kernel: snd_hda_intel 0000:01:00.1: can't change power state from D3cold to D0 (config space inaccessible)
kernel: snd_hda_codec_hdmi hdaudioC1D0: Unable to sync register 0x4f0800. -5
```

This seems to only occur on hybrid graphics mode.
Probably related to #160.

### PR DESCRIPTION
**Pull request by crawfxrd**
Increase the wait from 1 second to 5 seconds. Add it for hybrid graphics as well.

Resolves: system76/firmware-open#160
Resolves: system76/firmware-open#259

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]
I love magic sleeps

**Comment by crawfxrd** [comment]
system76/firmware-open#259 reports the issue using hybrid graphics. A sleep may need to be added in the `ONDEMAND` case as well.

**Comment by jacobgkau** [comment]
This does not seem to resolve https://github.com/system76/firmware-open/issues/160. I had some trouble recreating the issue even without the fix after upgrading the machine to Impish, but I got the issue again the first reboot after I installed this branch.

dmesg shows:
```
[   38.259574] nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
[   38.259663] snd_hda_intel 0000:01:00.1: can't change power state from D3cold to D0 (config space inaccessible)
[   38.260410] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x56:667)
[   38.260485] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   38.261135] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x56:667)
[   38.261189] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   38.643479] snd_hda_codec_hdmi hdaudioC1D0: Unable to sync register 0x4f0800. -5
```

nvidia-smi shows:
```
system76@pop-os:~$ apt policy gpu-manager
N: Unable to locate package gpu-manager
```

This was in Compute mode.

**Comment by crawfxrd** [comment]
If you set in manually by following the steps in #160, does it stop happening?

**Comment by crawfxrd** [comment]
This doesn't seem to resolve it, but it *is* being caused by configuring power management too early.

**Comment by JoonasC** [comment]
@crawfxrd Is there a way to check if the GPU has initialized, instead of waiting for a static amount of time?

**Comment by crawfxrd** [comment]
I don't know, hence the hack. Nothing in [Ch21](https://download.nvidia.com/XFree86/Linux-x86_64/470.86/README/powermanagement.html) or [Ch22](https://download.nvidia.com/XFree86/Linux-x86_64/470.86/README/dynamicpowermanagement.html) is useful. We can't enable the udev rule for the same reason.

So I think for now setting power management to auto needs to be removed from gpu-manager and udev and deferred like 30 seconds after boot in a separate unit.

**Comment by JoonasC** [comment]
@crawfxrd Maybe the GPU has some kind of interface you can try sending a command to, and you can interpret the operation failing as the GPU not being initialized?

**Comment by JoonasC** [comment]
For example, if there is an interface to get GPU model data, such as GPU name etc. You could maybe use that? Or would attempting to call a GPU interface while it's not initialized make the whole system fail?

**Comment by JoonasC** [comment]
Also this issue is most likely also linked to this: pop-os/pop#1750

**Comment by crawfxrd** [comment]
We finally have documentation from NVIDIA to implement GC-OFF and GC6, which should remove the need for the hack.

**Pull request closed without merging**
