### PR TITLE
Allow PRIME offloading with any GPUs

### PR DESCRIPTION
**Pull request by crawfxrd**
Remove the limitation of PRIME render offloading only being available for systems with an Intel iGPU used as the default display controller.

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@crawfxrd you might want to disable i386 builds for this. @brs17 this is needed to fully support https://github.com/pop-os/system76-power/pull/151

**Review by brs17 — APPROVED** [review]
Just took a look at this before the architecture patch was added. Once that builds successfully we can merge this.

**Comment by brs17** [comment]
This looks good @crawfxrd. Feel free to merge at your convenience.

**Comment by crawfxrd** [comment]
Was that not the correct way to limit it to amd64? It's still building ubuntu-drivers-common for i386.

**Comment by jackpot51** [comment]
Check the other packages for i386 being listed

**Comment by jackpot51** [comment]
There's two more instances in debian/control

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
