### PR TITLE
[jammy] Remove configuring X

### PR DESCRIPTION
**Pull request by crawfxrd**
Remove code configuring X server; system76-power handles this.

Requires: pop-os/system76-power#298

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — DISMISSED** [review]

**Comment by jackpot51** [comment]
The binaries did not appear to build

**Review by n3m0-22 — APPROVED** [review]
There were no issues with switching of power and graphics modes. The `ubuntu-drivers-common` CLI works as expected. Drivers are installable from both the terminal and pop-shop.

**Comment by jackpot51** [comment]
@n3m0-22 we also need https://github.com/pop-os/system76-power/pull/298 approved for both of these to be released at the same time

**Comment by n3m0-22** [comment]
It should be approved soon. Finishing some final checks on 20.04 now.

**Pull request merged**
